### ISSUE TITLE
Subscriptions ending if an ES node in a cluster shuts down gracefully.

### ISSUE THREAD

**Issue by sbmpost** [EventStore/EventStore.JVM#110] opened 2018-04-05 17:51 UTC
If a client subscribes to a stream (catch-up) and starts listening to the latest events, you would expect the subscription to endure forever: you are never unsubscribed unless something breaks. This does not seem to be the case if an ES node in a cluster shuts down gracefully. This may happen for example if OFFLINE TRUNCATION is needed for one of the nodes. If at that point the client happens to be connected to that very node it loses its subscriptions (it receives Unsubscribe).

It would be nicer if the ES library transferred the subscription to a different (still running) node without the need for the client to resubscribe (Note this is not about the connection itself which is properly re-established by the library).

Currently I am using an Akka RestartSource in the client as a workaround but I am not sure this approach is safe. I think it is quite possible to miss events in this way (but I am not sure). I guess my question is if this is a situation that should be solved in the library itself and if this is even technically possible without losing events.

**Comment by sbmpost** [comment] 2018-04-19 13:51
Ok! We will try with the RestartSource solution and maybe at some point this can dealt with in the library in the way you propose. Thanks for confirming and also curious what @t3hnar thinks of it :-)

**Comment by t3hnar** [comment] 2018-04-19 14:04
Hi I think this is a bug in the client. Client works with cluster and not with some node in particular, hence for all the operations that are idempotent (like subscribe) the switch between nodes should be invisible for the end users from logical perspective.

> It would be nicer if the ES library transferred the subscription to a different (still running) node without the need for the client to resubscribe

I can agree with this.

**Comment by reinierl** [comment] 2018-07-04 06:40
Isn't this issue now fixed by https://github.com/EventStore/EventStore.JVM/commit/87d89563f5fe7c9211ffab671592069c67aabc39?

**Comment by t3hnar** [comment] 2018-07-04 06:56
@reinierl looks so, curious whether you cannot reproduce this anymore with new client ?

**Comment by reinierl** [comment] 2018-07-04 08:28
OK, will try!

**Comment by reinierl** [comment] 2018-07-30 15:39
I can't reproduce it, thanks!

**Closed** 2018-07-30 18:19 UTC
Labels: bug
