### ISSUE TITLE
Subscription is lost after reconnect to ES

### ISSUE THREAD

**Issue by petraspaulauskas** [EventStore/EventStore.JVM#29] opened 2015-01-23 14:14 UTC
Subscription is created using EsConnection:
```
public Closeable subscribeToAllFrom(Position position, final EventObserver observer) {
        return connection.subscribeToAllFrom(new SubscriptionObserver<IndexedEvent>() {
            @Override
            public void onLiveProcessingStart(Closeable closeable) {
                numberOfSubscriptions.inc();
                logger.debug("Live processing: {}, total: {}", observer, numberOfSubscriptions.getCount());
            }

            @Override
            public void onEvent(IndexedEvent indexedEvent, Closeable closeable) {
                if (!isSystemEvent(indexedEvent)) {
                    try (Timer.Context ignored = allNonSystemEvents.time()) {
                        observer.onEvent(asSubscribed(indexedEvent));
                    }
                }
            }

            @Override
            public void onError(Throwable throwable) {
                logger.error("Error in subscription: " + observer, throwable);
            }

            @Override
            public void onClose() {
                numberOfSubscriptions.dec();
                logger.debug("Closed: {}, total: {}", observer, numberOfSubscriptions.getCount());
            }
        }, exactPosition(position), false, null);
    }
```

EventStore version: 3.0.0
client version: 1.0.1

After losing and reestablishing connection to EventStore, SubscriptionObserver is no longer receiving events. As I understand it, this is not an intended behavior?

**Comment by gregoryyoung** [comment] 2015-01-23 14:16
In the dotnet client you will lose your subscription as well but there is a
callback to tell you that this happened so you can reconnect it. Catchup
subscriptions automatically reconnect

On Friday, January 23, 2015, petraspaulauskas <notifications@github.com>
wrote:

> Subscription is created using EsConnection:
>
> public Closeable subscribeToAllFrom(Position position, final EventObserver observer) {
>         return connection.subscribeToAllFrom(new SubscriptionObserver<IndexedEvent>() {
>             @Override
>             public void onLiveProcessingStart(Closeable closeable) {
>                 numberOfSubscriptions.inc();
>                 logger.debug("Live processing: {}, total: {}", observer, numberOfSubscriptions.getCount());
>             }
>
>             @Override
>             public void onEvent(IndexedEvent indexedEvent, Closeable closeable) {
>                 if (!isSystemEvent(indexedEvent)) {
>                     try (Timer.Context ignored = allNonSystemEvents.time()) {
>                         observer.onEvent(asSubscribed(indexedEvent));
>                     }
>                 }
>             }
>
>             @Override
>             public void onError(Throwable throwable) {
>                 logger.error("Error in subscription: " + observer, throwable);
>             }
>
>             @Override
>             public void onClose() {
>                 numberOfSubscriptions.dec();
>                 logger.debug("Closed: {}, total: {}", observer, numberOfSubscriptions.getCount());
>             }
>         }, exactPosition(position), false, null);
>     }
>
> EventStore version: 3.0.0
> client version: 1.0.1
>
> After losing and reestablishing connection to EventStore,
> SubscriptionObserver is no longer receiving events. As I understand it,
> this is not an intended behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore.JVM/issues/29>.
>


-- 
Studying for the Turing test

**Comment by t3hnar** [comment] 2015-01-23 14:21
Thx for reporting this, it is not an intended behaviour

**Comment by t3hnar** [comment] 2015-01-23 14:31
@petraspaulauskas, not reproducible anymore on current `cluster` branch, there were many things changed. It will be released till the end of this month.

**Comment by t3hnar** [comment] 2015-01-30 19:13
fixed in https://github.com/EventStore/EventStore.JVM/releases/tag/v2.0.0

**Closed by t3hnar** 2015-01-30 19:13 UTC
